/* Generated by AN DISI Unibo */ 
package it.unibo.ioport

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import main.java.utils.*

class Ioport ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		 
				var contatore = 0 
			
				
				val RIL_CONTAINER_SECS=ProcessUtils.getIntEnvVar("RIL_CONTAINER_SECS").orElse(3)
				val RIL_ANOMALIA_SECS=ProcessUtils.getIntEnvVar("RIL_ANOMALIA_SECS").orElse(3)
				val SONAR_MIS_PER_SEC=ProcessUtils.getIntEnvVar("SONAR_MIS_PER_SEC").orElse(-1)
		
				if(SONAR_MIS_PER_SEC<0){
					println("Variabile d'ambiente SONAR_MIS_PER_SEC non presente o errata")
					System.exit(1)
				}
				
				val ContainerCounterTarget = SONAR_MIS_PER_SEC * RIL_CONTAINER_SECS
				val AnomaliaTargetCounter = SONAR_MIS_PER_SEC * RIL_ANOMALIA_SECS
				
			
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: STARTING...")
						subscribeToLocalActor("sonar") 
						subscribeToLocalActor("sonar") 
						subscribeToLocalActor("sonar") 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ioportVuota", cond=doswitch() )
				}	 
				state("ioportVuota") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: ioport vuota...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="resetPerContainer",cond=whenEvent("rilDistContainer"))
					transition(edgeName="t07",targetState="resetPerAnomalia",cond=whenEvent("rilDistAnomalia"))
				}	 
				state("resetPerContainer") { //this:State
					action { //it:State
						 contatore = 0  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="checkContainer", cond=doswitch() )
				}	 
				state("checkContainer") { //this:State
					action { //it:State
						 contatore += 1  
						if(  contatore == ContainerCounterTarget  
						 ){ contatore = 0  
						emit("containerRilevato", "containerRilevato(1)" ) 
						forward("continue", "continue(1)" ,name ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="containerRilevato",cond=whenDispatch("continue"))
					transition(edgeName="t09",targetState="checkContainer",cond=whenEvent("rilDistContainer"))
					transition(edgeName="t010",targetState="resetPerAnomalia",cond=whenEvent("rilDistAnomalia"))
					transition(edgeName="t011",targetState="ioportVuota",cond=whenEvent("rilDistVuoto"))
				}	 
				state("containerRilevato") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: container rilevato")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t012",targetState="resetPerAnomalia",cond=whenEvent("rilDistAnomalia"))
					transition(edgeName="t013",targetState="ioportVuota",cond=whenEvent("rilDistVuoto"))
				}	 
				state("resetPerAnomalia") { //this:State
					action { //it:State
						 contatore = 0  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="checkAnomalia", cond=doswitch() )
				}	 
				state("checkAnomalia") { //this:State
					action { //it:State
						 contatore += 1  
						if(  contatore == AnomaliaTargetCounter  
						 ){ contatore = 0  
						emit("rilevazioneAnomalia", "rilevazioneAnomalia(1)" ) 
						forward("continue", "continue(1)" ,name ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t014",targetState="anomalia",cond=whenDispatch("continue"))
					transition(edgeName="t015",targetState="resetPerContainer",cond=whenEvent("rilDistContainer"))
					transition(edgeName="t016",targetState="checkAnomalia",cond=whenEvent("rilDistAnomalia"))
					transition(edgeName="t017",targetState="ioportVuota",cond=whenEvent("rilDistVuoto"))
				}	 
				state("anomalia") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: anomalia in corso")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t018",targetState="fineAnomalia",cond=whenEvent("rilDistVuoto"))
				}	 
				state("fineAnomalia") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: fine anomalia")
						emit("risoluzioneAnomalia", "risoluzioneAnomalia(1)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ioportVuota", cond=doswitch() )
				}	 
			}
		}
} 
