services:
    
  webgui-frontend-alone:
    container_name: webgui-frontend-alone
    image: webgui-frontend:1.0
    ports:
      - 3000:3000/tcp
    networks:
      - iss-network
networks:
  iss-network:
    external: true

## yamls> docker network ls
## docker network create iss-network
## docker network rm xxx
## docker-compose -f webgui.yaml up
## docker compose -f webgui.yaml up
