/* Generated by AN DISI Unibo */ 
package it.unibo.led

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import java.io.*
import main.java.utils.*

class Led ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				val PYTHON_CMD = System.getenv("PYTHON_CMD") ?: ""
				if(PYTHON_CMD.equals("")){
					System.out.println("La variabile d'ambiente PYTHON_CMD non è impostata")
					System.exit(1)
				}
				
				val LED_ON_SCRIPT_PATH = System.getenv("LED_ON_SCRIPT_PATH") ?: ""
				val LED_OFF_SCRIPT_PATH = System.getenv("LED_OFF_SCRIPT_PATH") ?: ""
				if(LED_ON_SCRIPT_PATH.equals("") || LED_OFF_SCRIPT_PATH.equals("")){
					System.out.println("Le variabili d'ambiente LED_ON_SCRIPT_PATH e LED_OFF_SCRIPT_PATH non sono impostate")
					System.exit(1)
				}
				
				if(!File(LED_ON_SCRIPT_PATH).isFile() || !File(LED_OFF_SCRIPT_PATH).isFile()){
					System.out.println("Le variabili d'ambiente LED_ON_SCRIPT_PATH e LED_OFF_SCRIPT_PATH contengono percorsi inesistenti")
					System.exit(1)
				}
				 
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: STARTING...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ledOff", cond=doswitch() )
				}	 
				state("ledOff") { //this:State
					action { //it:State
						 
									val process = Runtime.getRuntime().exec(PYTHON_CMD+" "+LED_OFF_SCRIPT_PATH)
									val ledFisicoMsg = "led fisico: " + ProcessUtils.readAllStdOutput(process)
						CommUtils.outyellow(ledFisicoMsg)
						CommUtils.outyellow("$name: led spento")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="ledOn",cond=whenDispatch("accesioneLed"))
					transition(edgeName="t04",targetState="ledOff",cond=whenDispatch("spegnimentoLed"))
				}	 
				state("ledOn") { //this:State
					action { //it:State
						 
									val process = Runtime.getRuntime().exec(PYTHON_CMD+" "+LED_ON_SCRIPT_PATH)
									val ledFisicoMsg = "led fisico: " + ProcessUtils.readAllStdOutput(process)
						CommUtils.outyellow(ledFisicoMsg)
						CommUtils.outyellow("$name: led acceso")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="ledOn",cond=whenDispatch("accesioneLed"))
					transition(edgeName="t06",targetState="ledOff",cond=whenDispatch("spegnimentoLed"))
				}	 
			}
		}
} 
