/* Generated by AN DISI Unibo */ 
package it.unibo.productservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Productservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				//mock, poi sarà calcolato a partire dall'ultimo del db o in modo che in seguito
				//a riavvii rimanga univoco
				currentPID = 1	
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outcyan("$name: STARTING...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_requests", cond=doswitch() )
				}	 
				state("wait_requests") { //this:State
					action { //it:State
						CommUtils.outcyan("$name: in attesa di richieste...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="registrazione_prodotto",cond=whenRequest("registrazioneProdotto"))
					transition(edgeName="t01",targetState="recupera_prodotto",cond=whenRequest("recuperaProdotto"))
				}	 
				state("registrazione_prodotto") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("registrazioneProdotto(NOME,PESO)"), Term.createTerm("registrazioneProdotto(NOME,PESO)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val nome = payloadArg(0)
												val peso = payloadArg(1).toDouble()
												val PID = currentPID
												currentPID+=1
								CommUtils.outcyan("$name: prodotto $nome, $peso (PID $PID)")
								answer("registrazioneProdotto", "esitoRegistrazioneProdotto", "esitoRegistrazioneProdotto(PID)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_requests", cond=doswitch() )
				}	 
				state("recupera_prodotto") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("recuperaProdotto(PID)"), Term.createTerm("recuperaProdotto(PID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val PID = payloadArg(0).toInt()
								if(  PID == 1  
								 ){
													//mock per test
													val nome = "nome di test"
													val peso = "peso di test"	
								CommUtils.outcyan("$name: recuperato prodotto $nome, $peso (PID $PID)")
								answer("recuperaProdotto", "dettagliProdotto", "dettagliProdotto(pid,nome,peso)"   )  
								}
								else
								 {CommUtils.outcyan("$name: prodotto con PID $PID non trovato")
								 answer("recuperaProdotto", "prodottoNonTrovato", "prodottoNonTrovato("prodotto non trovato")"   )  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_requests", cond=doswitch() )
				}	 
			}
		}
} 
