/* Generated by AN DISI Unibo */ 
package it.unibo.productservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Productservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outcyan("$name: STARTING...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_requests", cond=doswitch() )
				}	 
				state("wait_requests") { //this:State
					action { //it:State
						CommUtils.outcyan("$name: in attesa di richieste...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="registrazione_prodotto",cond=whenRequest("registrazioneProdotto"))
					transition(edgeName="t01",targetState="recupera_prodotto",cond=whenRequest("recuperaProdotto"))
				}	 
				state("registrazione_prodotto") { //this:State
					action { //it:State
						answer("registrazioneProdotto", "esitoRegistrazioneProdotto", "esitoRegistrazioneProdotto(PID)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_requests", cond=doswitch() )
				}	 
				state("recupera_prodotto") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_requests", cond=doswitch() )
				}	 
			}
		}
} 
