/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				val maxPeso = 10000
				var slotLiberi = 4
				var pesoTotale = 0.0
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outred("$name: STARTING...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_requests", cond=doswitch() )
				}	 
				state("wait_requests") { //this:State
					action { //it:State
						CommUtils.outred("$name: in attesa di richieste...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="richiesta_carico_ricevuta",cond=whenRequest("richiestaCarico"))
					interrupthandle(edgeName="t03",targetState="anomalia_rilevata",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("richiesta_carico_ricevuta") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("richiestaCaricoCarico(PID)"), Term.createTerm("richiestaCarico(PID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
													val PID = payloadArg(0).toInt()
								CommUtils.outred("$name: ricevuta richiesta per caricamento prodotto con PID $PID")
								request("recuperaProdotto", "recuperaProdotto(PID)" ,"productservice" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="dati_prodotto_recuperati",cond=whenReply("dettagliProdotto"))
					transition(edgeName="t05",targetState="errore_recupero_prodotto",cond=whenReply("prodottoNonTrovato"))
					interrupthandle(edgeName="t06",targetState="anomalia_rilevata",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("errore_recupero_prodotto") { //this:State
					action { //it:State
						CommUtils.outred("$name: impossibile recuperare il prodotto con PID $PID")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_requests", cond=doswitch() )
				}	 
				state("dati_prodotto_recuperati") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("dettagliProdotto(PID,NOME,PESO)"), Term.createTerm("dettagliProdotto(PID,NOME,PESO)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
													val PID = payloadArg(0).toInt()
													val nome = payloadArg(1)
													val peso = payloadArg(2).toDouble()
								CommUtils.outred("$name: recuperati i dati del prodotto $nome, $peso PID $PID")
								if(  pesoTotale + peso <= maxPeso  
								 ){if(  slotLiberi > 0  
								 ){
														val slot=1	//mock
								
														slotLiberi-=1
														pesoTotale+=peso
								forward("caricamentoContainer", "caricamentoContainer(slot)" ,"cargorobot" ) 
								 statoStiva = "..."  
								emit("aggiornamentoStiva", "aggiornamentoStiva(statoStiva)" ) 
								}
								else
								 {CommUtils.outred("$name: richiesta rifiutata: nessuno slot disponibile")
								 answer("richiestaCarico", "richiestaCaricoRifiutata", "richiestaCaricoRifiutata("Nessuno slot disponibile")"   )  
								 forward("fine", "fine(1)" ,name ) 
								 }
								}
								else
								 {CommUtils.outred("$name: richiesta rifiutata: il peso eccede quello massimo")
								 answer("richiestaCarico", "richiestaCaricoRifiutata", "richiestaCaricoRifiutata("Il peso del prodotto eccede quello massimo")"   )  
								 forward("fine", "fine(1)" ,name ) 
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="wait_requests",cond=whenDispatch("fine"))
					transition(edgeName="t08",targetState="wait_requests",cond=whenEvent("fineCaricamentoContainer"))
					interrupthandle(edgeName="t09",targetState="anomalia_rilevata",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("anomalia_rilevata") { //this:State
					action { //it:State
						CommUtils.outred("$name: è stata ricevuta un'interruzione a seguito di un malfunzionamento del sonar")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t010",targetState="resume",cond=whenEvent("risoluzioneAnomalia"))
				}	 
				state("resume") { //this:State
					action { //it:State
						CommUtils.outred("$name: malfunzionamento del sonar risolto, ripresa delle attività")
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
