/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				//associazione slot occupati
				val pesoTot = 0.0	
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outred("$name: STARTING...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_requests", cond=doswitch() )
				}	 
				state("wait_requests") { //this:State
					action { //it:State
						CommUtils.outred("$name: in attesa di richieste...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="caricaProdotto",cond=whenRequest("richiestaCarico"))
					interrupthandle(edgeName="t02",targetState="anomalia_rilevata",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("caricaProdotto") { //this:State
					action { //it:State
						answer("richiestaCarico", "richiestaCaricoRifiutata", "richiestaCaricoAccettata("OK")"   )  
						answer("richiestaCarico", "richiestaCaricoRifiutata", "richiestaCaricoRifiutata("Motivazione rifiuto")"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_caricaProdotto", 
				 	 					  scope, context!!, "local_tout_"+name+"_caricaProdotto", 10.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t03",targetState="wait_requests",cond=whenTimeout("local_tout_"+name+"_caricaProdotto"))   
					interrupthandle(edgeName="t04",targetState="anomalia_rilevata",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("anomalia_rilevata") { //this:State
					action { //it:State
						CommUtils.outred("$name: è stata ricevuta un'interruzione a seguito di un malfunzionamento del sonar")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="wait_requests",cond=whenEvent("risoluzioneAnomalia"))
				}	 
			}
		}
} 
