services:

## -------------------------------------------------------------
## Useful services
## -------------------------------------------------------------

  mosquitto:
    image: eclipse-mosquitto:1.6.15
    container_name: mosquitto
    environment:
      - MQTT_ALLOW_ANONYMOUS=true   # Permette connessioni anonime
    ports:
      - 1883:1883
      - 9001:9001                   # Optional:Utilizzata per WebSocket MQTT
    networks:
      - iss-network

  mongodb:
    image: mongo:6.0.4
    container_name: mongodb  
    mem_limit: 512m
    environment:
      - MONGO_INITDB_DATABASE=cargodb # Nome del database da inizializzare
    ports:
      - "27017:27017"
    command: mongod
    networks:
      - iss-network

networks:
  iss-network:
    external: true

 

## yamls> docker network ls
## docker network create iss-network
## docker network rm xxx

## -------------------------------------------------------------
## TODO See https://docs.docker.com/compose/startup-order/
## -------------------------------------------------------------
## docker-compose -f utils.yaml  up
## docker compose -f utils.yaml  up
 
