/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import main.java.model.*

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				var CurrentSlot: Slot? = null
				
				var LastDestinationX = -1
				var LastDestinationY = -1
				
				val RobotStepTime = 350
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outcyan("$name: STARTING...")
						request("engage", "engage($MyName,$RobotStepTime)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="initDone",cond=whenReply("engagedone"))
					transition(edgeName="t01",targetState="initFailed",cond=whenReply("engagerefused"))
					interrupthandle(edgeName="t02",targetState="handleAnomalia",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("initFailed") { //this:State
					action { //it:State
						CommUtils.outcyan("$name: basicrobot engaging problem... shutting down")
						 System.exit(1)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("initDone") { //this:State
					action { //it:State
						forward("setplanbuildelay", "setplanbuildelay(0)" ,"basicrobot" ) 
						CommUtils.outcyan("$name: basicrobot engaged correctly")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitRequests", cond=doswitch() )
				}	 
				state("waitRequests") { //this:State
					action { //it:State
						
									LastDestinationX = -1
									LastDestinationY = -1
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="processRichiestaCaricamentoSlot",cond=whenRequest("richiestaCaricamentoSlot"))
					interrupthandle(edgeName="t04",targetState="handleAnomalia",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("processRichiestaCaricamentoSlot") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("richiestaCaricamentoSlot(SlotJson)"), Term.createTerm("richiestaCaricamentoSlot(SlotJson)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val SlotJson = payloadArg(0).toString()
												CurrentSlot = Slot(SlotJson)
								CommUtils.outcyan("$name: $CurrentSlot")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="goToIOPort", cond=doswitch() )
				}	 
				state("goToIOPort") { //this:State
					action { //it:State
						CommUtils.outcyan("$name: going to IOPort...")
						
									LastDestinationX = 4
									LastDestinationY = 0
						request("moverobot", "moverobot(4,0,$RobotStepTime)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="atIOPort",cond=whenReply("moverobotdone"))
					transition(edgeName="t06",targetState="moveFailed",cond=whenReply("moverobotfailed"))
					interrupthandle(edgeName="t07",targetState="handleAnomalia",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("atIOPort") { //this:State
					action { //it:State
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="goToSlot", cond=doswitch() )
				}	 
				state("goToSlot") { //this:State
					action { //it:State
						
									val SlotPosX = CurrentSlot!!.getPosX()
									val SlotPosY = CurrentSlot!!.getPosY()
									
									LastDestinationX = CurrentSlot!!.getLoadingPosX()
									LastDestinationY = CurrentSlot!!.getLoadingPosY()
						CommUtils.outcyan("$name: going to slot ($SlotPosX, $SlotPosY) ($LastDestinationX, $LastDestinationY)...")
						request("moverobot", "moverobot($LastDestinationX,$LastDestinationY,$RobotStepTime)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="atSlot",cond=whenReply("moverobotdone"))
					transition(edgeName="t09",targetState="moveFailed",cond=whenReply("moverobotfailed"))
					interrupthandle(edgeName="t010",targetState="handleAnomalia",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("atSlot") { //this:State
					action { //it:State
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="goToHome", cond=doswitch() )
				}	 
				state("goToHome") { //this:State
					action { //it:State
						
									CurrentSlot = null
						CommUtils.outcyan("$name: going to HOME...")
						answer("richiestaCaricamentoSlot", "slotCaricato", "slotCaricato(0)"   )  
						
									LastDestinationX = 0
									LastDestinationY = 0
						request("moverobot", "moverobot(0,0,340)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="atHome",cond=whenReply("moverobotdone"))
					transition(edgeName="t012",targetState="moveFailed",cond=whenReply("moverobotfailed"))
					transition(edgeName="t013",targetState="serviRichiestaPrimaDiHome",cond=whenRequest("richiestaCaricamentoSlot"))
					interrupthandle(edgeName="t014",targetState="handleAnomalia",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("atHome") { //this:State
					action { //it:State
						request("tuneAtHome", "tuneAtHome(ok)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t015",targetState="waitRequests",cond=whenReply("tuneDone"))
				}	 
				state("serviRichiestaPrimaDiHome") { //this:State
					action { //it:State
						
									LastDestinationX = -1
									LastDestinationY = -1
						emit("alarm", "alarm(0)" ) 
						if( checkMsgContent( Term.createTerm("richiestaCaricamentoSlot(SlotJson)"), Term.createTerm("richiestaCaricamentoSlot(SlotJson)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val SlotJson = payloadArg(0).toString()
												CurrentSlot = Slot(SlotJson)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="goToIOPort", cond=doswitch() )
				}	 
				state("handleAnomalia") { //this:State
					action { //it:State
						CommUtils.outcyan("$name: rilevazione anomalia...")
						emit("alarm", "alarm(0)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t016",targetState="resumeFromAnomalia",cond=whenEvent("risoluzioneAnomalia"))
				}	 
				state("resumeFromAnomalia") { //this:State
					action { //it:State
						CommUtils.outcyan("$name: anomalia risolta...")
						if(  LastDestinationX != -1 && LastDestinationY != -1  
						 ){request("moverobot", "moverobot($LastDestinationX,$LastDestinationY,$RobotStepTime)" ,"basicrobot" )  
						}
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("moveFailed") { //this:State
					action { //it:State
						answer("richiestaCaricamentoSlot", "caricamentoFallito", "caricamentoFallito(1)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitRequests", cond=doswitch() )
				}	 
			}
		}
} 
