/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "initi"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				DFREE = 11
				var D = 0.0	
		return { //this:ActionBasciFsm
				state("initi") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: STARTING...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t013",targetState="waitMisurazioni",cond=whenEvent("rilevazioneDistanza"))
				}	 
				state("waitMisurazioni") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("rilevazioneDistanza(X)"), Term.createTerm("rilevazioneDistanza(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												D = payloadArg(0).toDouble()
								if(  D <= DFREE/2  
								 ){emitLocalStreamEvent("rilDistContainer", "rilDistContainer(1)" ) 
								}
								else
								 {if(  D > DFREE  
								  ){emitLocalStreamEvent("rilDistAnomalia", "rilDistAnomalia(1)" ) 
								 }
								 else
								  {emitLocalStreamEvent("rilDistVuoto", "rilDistVuoto(1)" ) 
								  }
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t014",targetState="waitMisurazioni",cond=whenEvent("rilevazioneDistanza"))
				}	 
			}
		}
} 
