/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import java.io.*

class Sonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				val PYTHON_CMD = System.getenv("PYTHON_CMD") ?: ""
				if(PYTHON_CMD.equals("")){
					System.out.println("La variabile d'ambiente PYTHON_CMD non è impostata")
					System.exit(1)
				}
				
				val SONAR_SCRIPT_PATH = System.getenv("LED_ON_SCRIPT_PATH") ?: ""
				if(SONAR_SCRIPT_PATH.equals("")){
					System.out.println("La variabile d'ambiente SONAR_SCRIPT_PATH non è impostata")
					System.exit(1)
				}
				
				if(!File(SONAR_SCRIPT_PATH).isFile()){
					System.out.println("La variabile d'ambiente SONAR_SCRIPT_PATH contiene un percorso inesistente")
					System.exit(1)
				}
				
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: STARTING...")
						if(  DFREE_CALIBRATION_FLAG == 0  
						 ){CommUtils.outyellow("$name: DFREE=${DFREE}")
						}
						subscribeToLocalActor("lettore_sonar_fisico") 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="waitMisurazioni",cond=whenEventGuarded("rilevazioneDistanza",{ DFREE_CALIBRATION_FLAG == 0  
					}))
					transition(edgeName="t01",targetState="calibrazione",cond=whenEventGuarded("rilevazioneDistanza",{ DFREE_CALIBRATION_FLAG == 1  
					}))
				}	 
				state("calibrazione") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("rilevazioneDistanza(X)"), Term.createTerm("rilevazioneDistanza(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val D = payloadArg(0).toDouble()
								CommUtils.outyellow("$name: calibrazione in corso [${counterCalibrazione}/${TargetCounterCalibrazione}]...")
								if(  counterCalibrazione < TargetCounterCalibrazione  
								 ){
													if(D > DFREE){
														DFREE = D
													}
													counterCalibrazione += 1
								}
								else
								 {
								 					//DFREE = DFREE/TargetCounterCalibrazione
								 forward("continue", "continue(1)" ,name ) 
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="endCalibrazione",cond=whenDispatch("continue"))
					transition(edgeName="t03",targetState="calibrazione",cond=whenEvent("rilevazioneDistanza"))
				}	 
				state("endCalibrazione") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: calibrazione terminata, DFREE=${DFREE}")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="waitMisurazioni",cond=whenEvent("rilevazioneDistanza"))
				}	 
				state("waitMisurazioni") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("rilevazioneDistanza(X)"), Term.createTerm("rilevazioneDistanza(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val D = payloadArg(0).toDouble()
								CommUtils.outyellow("$name: ricevuto D=${D}")
								if(  D <= DFREE/2  
								 ){emitLocalStreamEvent("rilDistContainer", "rilDistContainer(1)" ) 
								}
								else
								 {if(  D > DFREE  
								  ){emitLocalStreamEvent("rilDistAnomalia", "rilDistAnomalia(1)" ) 
								 }
								 else
								  {emitLocalStreamEvent("rilDistVuoto", "rilDistVuoto(1)" ) 
								  }
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="waitMisurazioni",cond=whenEvent("rilevazioneDistanza"))
				}	 
			}
		}
} 
