/* Generated by AN DISI Unibo */ 
package it.unibo.lettore_sonar_fisico

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import main.java.utils.*

class Lettore_sonar_fisico ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				
				val PYTHON_CMD = ProcessUtils.getStringEnvVar("PYTHON_CMD").orElse("")
				if(PYTHON_CMD.equals("")){
					System.out.println("La variabile d'ambiente PYTHON_CMD non è impostata")
					System.exit(1)
				}
				
				val SONAR_SCRIPT_PATH = ProcessUtils.getStringEnvVar("SONAR_SCRIPT_PATH").orElse("")
				if(SONAR_SCRIPT_PATH.equals("")){
					System.out.println("La variabile d'ambiente SONAR_SCRIPT_PATH non è impostata")
					System.exit(1)
				}
				
				if(!java.io.File(SONAR_SCRIPT_PATH).isFile()){
					System.out.println("La variabile d'ambiente SONAR_SCRIPT_PATH contiene un percorso inesistente")
					System.exit(1)
				}
				
				val process = Runtime.getRuntime().exec(PYTHON_CMD + " -u " + SONAR_SCRIPT_PATH) 
		    	val reader = java.io.BufferedReader(java.io.InputStreamReader(process.inputStream))
		    	
		    	
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: STARTING...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
				state("working") { //this:State
					action { //it:State
						
									val line = reader.readLine()
									
									if(line == null){
										System.out.println("Problema rilevamento distanza")
										println(line)
										System.exit(1)
									}
									
									val D = line.toDoubleOrNull() ?: -1.0
									
									if(D<0){
										System.out.println("Problema rilevamento distanza")
										System.exit(1)
									}
									
						delay(1000) 
						CommUtils.outcyan(D)
						emitLocalStreamEvent("rilevazioneDistanza", "rilevazioneDistanza($D)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
			}
		}
} 
