services:

  ioport:
    container_name: ioport
    image: ioport:1.0
    ports:
      - 9093:9093/tcp
      - 9093:9093/udp
    extra_hosts:
      - "cargoservice:192.168.1.192"
      - "cargorobot:192.168.1.192"
    networks:
      - ext-net
    environment:
      - DFREE_CALIBRATION_FLAG=1
      - DFREE=10
      - RIL_CONTAINER_SECS=3
      - RIL_ANOMALIA_SECS=3
      - SONAR_MIS_PER_SEC=1
      - PYTHON_CMD=python3
      - SONAR_SCRIPT_PATH=/resources/python/sonar.py
      - LED_OFF_SCRIPT_PATH=/resources/python/ledPython25Off.py
      - LED_ON_SCRIPT_PATH=/resources/python/ledPython25On.py
    volumes:
      - ./ledPython25On.py:/resources/python/ledPython25On.py
      - ./ledPython25Off.py:/resources/python/ledPython25Off.py
      - ./sonar.py:/resources/python/sonar.py

networks:
  iss-network:
    external: true
  ext-net:
    driver: bridge
