/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import main.java.utils.*

class Sonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				
				val DFREE_CALIBRATION_FLAG = ProcessUtils.getIntEnvVar("DFREE_CALIBRATION_FLAG").orElse(0)
				var DFREE = -1.0
				if(DFREE_CALIBRATION_FLAG == 0){
					DFREE = ProcessUtils.getDoubleEnvVar("DFREE").orElse(-1.0)
					if(DFREE<0.0){
						println("Variabile d'ambiente DFREE non presente o errata")
						System.exit(1)
					}
				}
				
				val SONAR_MIS_PER_SEC=ProcessUtils.getIntEnvVar("SONAR_MIS_PER_SEC").orElse(-1)
		
				if(SONAR_MIS_PER_SEC<0){
					println("Variabile d'ambiente SONAR_MIS_PER_SEC non presente o errata")
					System.exit(1)
				}
				
				val TargetCounterCalibrazione = SONAR_MIS_PER_SEC * 10
				
				var counterCalibrazione = 0
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: STARTING...")
						if(  DFREE_CALIBRATION_FLAG == 0  
						 ){CommUtils.outyellow("$name: DFREE=${DFREE}")
						}
						subscribeToLocalActor("lettore_sonar_fisico") 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t043",targetState="waitMisurazioni",cond=whenEventGuarded("rilevazioneDistanza",{ DFREE_CALIBRATION_FLAG == 0  
					}))
					transition(edgeName="t044",targetState="calibrazione",cond=whenEventGuarded("rilevazioneDistanza",{ DFREE_CALIBRATION_FLAG == 1  
					}))
				}	 
				state("calibrazione") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("rilevazioneDistanza(X)"), Term.createTerm("rilevazioneDistanza(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val D = payloadArg(0).toDouble()
								CommUtils.outyellow("$name: calibrazione in corso [${counterCalibrazione}/${TargetCounterCalibrazione}]...")
								if(  counterCalibrazione < TargetCounterCalibrazione  
								 ){
													if(D > DFREE){
														DFREE = D
													}
													counterCalibrazione += 1
								}
								else
								 {
								 					//DFREE = DFREE/TargetCounterCalibrazione
								 forward("continue", "continue(1)" ,name ) 
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t045",targetState="endCalibrazione",cond=whenDispatch("continue"))
					transition(edgeName="t046",targetState="calibrazione",cond=whenEvent("rilevazioneDistanza"))
				}	 
				state("endCalibrazione") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: calibrazione terminata, DFREE=${DFREE}")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t047",targetState="waitMisurazioni",cond=whenEvent("rilevazioneDistanza"))
				}	 
				state("waitMisurazioni") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("rilevazioneDistanza(X)"), Term.createTerm("rilevazioneDistanza(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val D = payloadArg(0).toDouble()
								CommUtils.outyellow("$name: ricevuto D=${D}")
								if(  D <= DFREE/2  
								 ){emitLocalStreamEvent("rilDistContainer", "rilDistContainer(1)" ) 
								}
								else
								 {if(  D > DFREE  
								  ){emitLocalStreamEvent("rilDistAnomalia", "rilDistAnomalia(1)" ) 
								 }
								 else
								  {emitLocalStreamEvent("rilDistVuoto", "rilDistVuoto(1)" ) 
								  }
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t048",targetState="waitMisurazioni",cond=whenEvent("rilevazioneDistanza"))
				}	 
			}
		}
} 
