/* Generated by AN DISI Unibo */ 
package it.unibo.cargo_service

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargo_service ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
			const maxLoad = 100;
			var currentWeight = 0;  
			var currentPID = ""
			
			var slotOne = true; 
			var slotTwo = true; 
			var slotThree = true;  
			var slotFour = true;  
			
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblack("$name| active")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitForRequest", cond=doswitch() )
				}	 
				state("waitForRequest") { //this:State
					action { //it:State
						CommUtils.outblack("$name| in attesa di richiesta")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="checkRequest",cond=whenRequest("requestCargo"))
				}	 
				state("checkRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("cargo_request(PID)"), Term.createTerm("cargo_request(PID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var check = /* richiesta soddisfacibile? */  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitPositioning", cond=doswitchGuarded({ check  
					}) )
					transition( edgeName="goto",targetState="waitForRequest", cond=doswitchGuarded({! ( check  
					) }) )
				}	 
				state("waitPositioning") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="putCargo",cond=whenEvent("sonarDetect"))
					transition(edgeName="t03",targetState="sendAlarm",cond=whenEvent("sonarError"))
				}	 
				state("putCargo") { //this:State
					action { //it:State
						forward("putInSlot", "put_in_slot(SLOT)" ,"cargorobot" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitForRobot", cond=doswitch() )
				}	 
				state("waitForRobot") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t24",targetState="waitForRequest",cond=whenDispatch("positioned"))
					transition(edgeName="t25",targetState="sendAlarm",cond=whenEvent("sonarError"))
				}	 
				state("sendAlarm") { //this:State
					action { //it:State
						emit("alarm", "alarm(X)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitForAlarmEnd", cond=doswitch() )
				}	 
				state("waitForAlarmEnd") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t36",targetState="alarmEnded",cond=whenEvent("sonarDetect"))
					transition(edgeName="t37",targetState="waitForAlarmEnd",cond=whenEvent("sonarError"))
				}	 
				state("alarmEnded") { //this:State
					action { //it:State
						emit("alarmEnded", "alarmEnded(X)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
