/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import main.java.model.*
import main.java.dto.*
import java.io.IOException

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				val MAX_LOAD = System.getenv("MAX_LOAD").toIntOrNull() ?: -1
				if(MAX_LOAD<=0){
					System.out.println("La variabile d'ambinete MAX_LOAD non è settata correttamente o è un numero <=0")
					System.exit(1)
				}
				
				var slotMap: SlotMap? = null
				try{
					slotMap = CargoSlotMap("slotmap-conf.json")
				}
				catch(e: IOException){
					System.exit(1)
				}
				var currentProduct: Product? = null
				var currentSlot: Slot? = null
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outred("$name: STARTING...")
						updateResourceRep( StatoStivaDTO(slotMap!!.getIdMap(), MAX_LOAD).toString()  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_requests", cond=doswitch() )
				}	 
				state("wait_requests") { //this:State
					action { //it:State
						CommUtils.outred("$name: in attesa di richieste...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="elaboraRichiesta",cond=whenRequest("richiestaCarico"))
					transition(edgeName="t01",targetState="handleResetStiva",cond=whenRequest("resetStiva"))
					interrupthandle(edgeName="t02",targetState="handleAnomalia",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("elaboraRichiesta") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("richiestaCarico(PID)"), Term.createTerm("richiestaCarico(PID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val ID = payloadArg(0).toInt()
								CommUtils.outred("$name: ricevuta richiesta di caricamento per il prodotto $ID")
								request("getProduct", "product($ID)" ,"productservice" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="datiProdottoRicevuti",cond=whenReply("getProductAnswer"))
					interrupthandle(edgeName="t04",targetState="handleAnomalia",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("datiProdottoRicevuti") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("product(JSonString)"), Term.createTerm("product(JSonString)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val JsonString = payloadArg(0).toString()
												currentProduct = Product(JsonString)
								if(  currentProduct!!.getProductId() <= 0  
								 ){CommUtils.outred("$name: il prodotto richiesto non esiste")
								 val Esito = "'Prodotto non esistente'" 
								answer("richiestaCarico", "richiestaCaricoRifiutata", "richiestaCaricoRifiutata($Esito)"   )  
								forward("endLocal", "endLocal(0)" ,name ) 
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_datiProdottoRicevuti", 
				 	 					  scope, context!!, "local_tout_"+name+"_datiProdottoRicevuti", 10.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t05",targetState="assegnamentoSlot",cond=whenTimeout("local_tout_"+name+"_datiProdottoRicevuti"))   
					transition(edgeName="t06",targetState="wait_requests",cond=whenDispatch("endLocal"))
					interrupthandle(edgeName="t07",targetState="handleAnomalia",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("assegnamentoSlot") { //this:State
					action { //it:State
						CommUtils.outred("$name: recuperati i dati del prodotto")
						if(  !slotMap!!.isAnySlotEmpty()  
						 ){CommUtils.outred("$name: richiesta rifiutata, nessuno slot disponibile")
						 val Esito = "'Nessuno slot disponibile'" 
						answer("richiestaCarico", "richiestaCaricoRifiutata", "richiestaCaricoRifiutata($Esito)"   )  
						forward("endLocal", "endLocal(0)" ,name ) 
						}
						else
						 {if(  slotMap!!.getTotalWeight() + currentProduct!!.getWeight() > MAX_LOAD  
						  ){CommUtils.outred("$name: richiesta rifiutata, peso eccessivo")
						  val Esito = "'Il prodotto eccede il peso massimo della stiva'" 
						 answer("richiestaCarico", "richiestaCaricoRifiutata", "richiestaCaricoRifiutata($Esito)"   )  
						 forward("endLocal", "endLocal(0)" ,name ) 
						 }
						 else
						  { 
						  					currentSlot = slotMap!!.getFirstEmptySlot()
						  					slotMap!!.putProductIntoSlot(currentSlot, currentProduct)
						  					val Esito = "'OK'"
						  updateResourceRep( StatoStivaDTO(slotMap!!.getIdMap(), MAX_LOAD).toString()  
						  )
						  CommUtils.outred("$name: prodotto assegnato allo slot $currentSlot")
						  answer("richiestaCarico", "richiestaCaricoAccettata", "richiestaCaricoAccettata($Esito)"   )  
						  }
						 }
						
									currentProduct = null	
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_assegnamentoSlot", 
				 	 					  scope, context!!, "local_tout_"+name+"_assegnamentoSlot", 10.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t08",targetState="waitContainer",cond=whenTimeout("local_tout_"+name+"_assegnamentoSlot"))   
					transition(edgeName="t09",targetState="wait_requests",cond=whenDispatch("endLocal"))
					interrupthandle(edgeName="t010",targetState="handleAnomalia",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("waitContainer") { //this:State
					action { //it:State
						CommUtils.outred("$name: in attesa che il container venga messo davanti all'IOPort")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="caricaProdotto",cond=whenEvent("containerRilevato"))
					interrupthandle(edgeName="t012",targetState="handleAnomalia",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("caricaProdotto") { //this:State
					action { //it:State
						CommUtils.outred("$name: caricamento prodotto da parte del cargorobot iniziato")
						
									val SlotJson = "\'" + currentSlot.toString() + "\'" 
									currentSlot=null
						request("richiestaCaricamentoSlot", "richiestaCaricamentoSlot($SlotJson)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t013",targetState="caricamentoTerminato",cond=whenReply("slotCaricato"))
					transition(edgeName="t014",targetState="problemaCaricamento",cond=whenReply("caricamentoFallito"))
					interrupthandle(edgeName="t015",targetState="handleAnomalia",cond=whenEvent("rilevazioneAnomalia"),interruptedStateTransitions)
				}	 
				state("caricamentoTerminato") { //this:State
					action { //it:State
						CommUtils.outred("$name: caricamento del prodotto nello slot completato correttamente")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_requests", cond=doswitch() )
				}	 
				state("problemaCaricamento") { //this:State
					action { //it:State
						CommUtils.outred("$name: problema nel caricamento da parte del cargorobot")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_requests", cond=doswitch() )
				}	 
				state("handleAnomalia") { //this:State
					action { //it:State
						CommUtils.outred("$name: rilevazione anomalia...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t016",targetState="resumeFromAnomalia",cond=whenEvent("risoluzioneAnomalia"))
				}	 
				state("resumeFromAnomalia") { //this:State
					action { //it:State
						CommUtils.outred("$name: anomalia risolta...")
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handleResetStiva") { //this:State
					action { //it:State
						 slotMap = CargoSlotMap("slotmap-conf.json")  
						updateResourceRep( StatoStivaDTO(slotMap!!.getIdMap(), MAX_LOAD).toString()  
						)
						answer("resetStiva", "esitoResetStiva", "esitoResetStiva(0)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_requests", cond=doswitch() )
				}	 
			}
		}
} 
